(deftheme cyberpunk
  "Created 2018-12-27.")

(custom-theme-set-variables
 'cyberpunk
 '(ansi-color-names-vector ["#000000" "#8b0000" "#00ff00" "#ffa500" "#7b68ee" "#dc8cc3" "#93e0e3" "#dcdccc"]))

(custom-theme-set-faces
 'cyberpunk
 '(button ((t (:underline t))))
 '(link ((((class color) (min-colors 89)) (:foreground "#ffff00" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#d0bf8f" :underline t :weight normal))))
 '(bold ((((class color) (min-colors 89)) (:bold t))))
 '(cursor ((((class color) (min-colors 89)) (:background "#dcdccc"))))
 '(fringe ((((class color) (min-colors 89)) (:foreground "#dcdccc" :background "#2b2b2b"))))
 '(header-line ((((class color) (min-colors 89)) (:foreground "#ffff00" :background "#2b2b2b" :box (:line-width -1 :style released-button)))))
 '(highlight ((((class color) (min-colors 89)) (:background "#333333"))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#bfebbf" :underline t))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#ffff00"))))
 '(match ((((class color) (min-colors 89)) (:background "#000000" :foreground "#ff1493"))))
 '(mc/cursor-face ((((class color) (min-colors 89)) (:inverse-video nil :background "#ff69b4" :foreground "#000000"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#000000" :background "#ff1493"))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#8b0000"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#000000" :background "#ffff00"))))
 '(query-replace ((((class color) (min-colors 89)) (:background "#333333"))))
 '(menu ((((class color) (min-colors 89)) (:foreground "#dcdccc" :background "#000000"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#61CE3C" :background "#000000"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#4c83ff" :background "#333333" :box (:line-width -1 :color "#4c83ff")))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#4D4D4D" :background "#1A1A1A" :box (:line-width -1 :color "#4c83ff")))))
 '(region ((((class color) (min-colors 89)) (:background "#7F073F"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#5f5f5f"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#ff0000"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#333333" :background "#000000"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#4c83ff"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#8B8989" :italic t))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#96CBFE"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#FBDE2D"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#ff1493"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#4c83ff"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#919191"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#61CE3C"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#afd8af"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#ff69b4"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#ff69b4"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#E9C062"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#ff0000"))))
 '(c-annotation-face ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#8B8989" :foreground "#ffff00"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#0000ff"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:inherit company-tooltip-selection :foreground "#0000ff"))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:foreground "#000000" :background "#ff1493"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#0A0A0A"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#0A0A0A"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#333333"))))
 '(company-preview ((((class color) (min-colors 89)) (:foreground "#d3d3d3" :background "#ff1493"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:foreground "#d3d3d3" :background "#ff1493"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#00ff00"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#ffff00"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#ff0000"))))
 '(diff-header ((((class color) (min-colors 89)) (:background "#5f5f5f"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "#5f5f5f" :foreground "#dcdccc" :bold t))))
 '(eshell-prompt ((((class color) (min-colors 89)) (:foreground "#4c83ff" :weight bold))))
 '(eshell-ls-archive ((((class color) (min-colors 89)) (:foreground "#dc8cc3" :weight bold))))
 '(eshell-ls-backup ((((class color) (min-colors 89)) (:inherit font-lock-comment))))
 '(eshell-ls-clutter ((((class color) (min-colors 89)) (:inherit font-lock-comment))))
 '(eshell-ls-directory ((((class color) (min-colors 89)) (:foreground "#94bff3" :weight bold))))
 '(eshell-ls-executable ((((class color) (min-colors 89)) (:foreground "#dca3a3" :weight bold))))
 '(eshell-ls-unreadable ((((class color) (min-colors 89)) (:foreground "#dcdccc"))))
 '(eshell-ls-missing ((((class color) (min-colors 89)) (:inherit font-lock-warning))))
 '(eshell-ls-product ((((class color) (min-colors 89)) (:inherit font-lock-doc))))
 '(eshell-ls-special ((((class color) (min-colors 89)) (:foreground "#ffff00" :weight bold))))
 '(eshell-ls-symlink ((((class color) (min-colors 89)) (:foreground "#93e0e3" :weight bold))))
 '(flymake-error ((((class color) (min-colors 89)) (:foreground "#8b0000" :weight bold :underline t))))
 '(flymake-warning ((((class color) (min-colors 89)) (:foreground "#FBDE2D" :weight bold :underline t))))
 '(helm-header ((((class color) (min-colors 89)) (:foreground "#00ff00" :background "#000000" :underline nil :box nil))))
 '(helm-source-header ((((class color) (min-colors 89)) (:foreground "#ffff00" :background "#2b2b2b" :underline nil :weight bold :box (:line-width -1 :style released-button)))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#2b2b2b" :underline nil))))
 '(helm-selection-line ((((class color) (min-colors 89)) (:background "#4f4f4f"))))
 '(helm-visible-mark ((((class color) (min-colors 89)) (:foreground "#000000" :background "#d0bf8f"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:foreground "#bfebbf" :background "#2b2b2b"))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:foreground "#ff69b4" :background "#000000"))))
 '(helm-ff-dotted-directory ((((class color) (min-colors 89)) (:foreground "#ff69b4" :background "#000000"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#ff1493" :background "#000000"))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#ff1493" :background "#000000"))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#999999" :backgroun "#000000"))))
 '(ido-indicator ((((class color) (min-colors 89)) (:foreground "#000000" :background "#ff1493"))))
 '(magit-section-highlight ((t (:background "#4f4f4f"))))
 '(magit-section-heading ((t (:foreground "#94bff3" :weight bold))))
 '(magit-section-heading-selection ((t (:foreground "#dca3a3" :weight bold))))
 '(magit-diff-file-heading ((t (:weight bold))))
 '(magit-diff-file-heading-highlight ((t (:background "#5f5f5f" :weight bold))))
 '(magit-diff-file-heading-selection ((t (:background "#5f5f5f" :foreground "#96CBFE" :weight bold))))
 '(magit-diff-hunk-heading ((t (:background "#000000"))))
 '(magit-diff-hunk-heading-highlight ((t (:background "#4f4f4f"))))
 '(magit-diff-hunk-heading-selection ((t (:background "#4f4f4f" :foreground "#96CBFE"))))
 '(magit-diff-lines-heading ((t (:background "#96CBFE" :foreground "#4f4f4f"))))
 '(magit-diff-added ((t (:foreground "#4c83ff"))))
 '(magit-diff-added-highlight ((t (:inherit magit-diff-added :weight bold))))
 '(magit-diff-removed ((t (:foreground "#dc8cc3"))))
 '(magit-diff-removed-highlight ((t (:inherit magit-diff-removed :weight bold))))
 '(magit-diff-context ((t (:foreground "#d3d3d3"))))
 '(magit-diff-context-highlight ((t (:inherit magit-diff-context :weight bold))))
 '(magit-diffstat-added ((t (:inherit magit-diff-added))))
 '(magit-diffstat-removed ((t (:inherit magit-diff-removed))))
 '(magit-popup-heading ((t (:foreground "#ff1493" :weight bold))))
 '(magit-popup-key ((t (:foreground "#94bff3" :weight bold))))
 '(magit-popup-argument ((t (:foreground "#b2dfee" :weight bold))))
 '(magit-popup-disabled-argument ((t (:foreground "#dcdccc" :weight normal))))
 '(magit-popup-option-value ((t (:foreground "#6a5acd" :weight bold))))
 '(magit-process-ok ((t (:foreground "#61CE3C" :weight bold))))
 '(magit-process-ng ((t (:foreground "#cd1076" :weight bold))))
 '(magit-log-author ((t (:foreground "#ff69b4"))))
 '(magit-log-date ((t (:foreground "#d3d3d3"))))
 '(magit-log-graph ((t (:foreground "#F8F8F8"))))
 '(magit-sequence-pick ((t (:foreground "#dc8cc3"))))
 '(magit-sequence-stop ((t (:foreground "#61CE3C"))))
 '(magit-sequence-part ((t (:foreground "#ff1493"))))
 '(magit-sequence-head ((t (:foreground "#94bff3"))))
 '(magit-sequence-drop ((t (:foreground "#ffa500"))))
 '(magit-sequence-done ((t (:foreground "#8B8989"))))
 '(magit-sequence-onto ((t (:foreground "#8B8989"))))
 '(magit-bisect-good ((t (:foreground "#61CE3C"))))
 '(magit-bisect-skip ((t (:foreground "#ff1493"))))
 '(magit-bisect-bad ((t (:foreground "#ffa500"))))
 '(magit-blame-heading ((t (:background "#4f4f4f" :foreground "#00ff00"))))
 '(magit-blame-hash ((t (:background "#4f4f4f" :foreground "#00ff00"))))
 '(magit-blame-name ((t (:background "#4f4f4f" :foreground "#ff1493"))))
 '(magit-blame-date ((t (:background "#4f4f4f" :foreground "#FBDE2D"))))
 '(magit-blame-summary ((t (:background "#4f4f4f" :foreground "#b2dfee" :weight bold))))
 '(magit-dimmed ((t (:foreground "#6f6f6f"))))
 '(magit-hash ((t (:foreground "#4f4f4f"))))
 '(magit-tag ((t (:foreground "#ff1493" :weight bold))))
 '(magit-branch-remote ((t (:foreground "#9fc59f" :weight bold))))
 '(magit-branch-local ((t (:foreground "#94bff3" :weight bold))))
 '(magit-branch-current ((t (:foreground "#00ff00" :weight bold :box t))))
 '(magit-head ((t (:foreground "#0000ff" :weight bold))))
 '(magit-refname ((t (:background "#5f5f5f" :foreground "#dcdccc" :weight bold))))
 '(magit-refname-stash ((t (:background "#5f5f5f" :foreground "#dcdccc" :weight bold))))
 '(magit-refname-wip ((t (:background "#5f5f5f" :foreground "#dcdccc" :weight bold))))
 '(magit-signature-good ((t (:foreground "#00ff00"))))
 '(magit-signature-bad ((t (:foreground "#ff0000"))))
 '(magit-signature-untrusted ((t (:foreground "#ffff00"))))
 '(magit-cherry-unmatched ((t (:foreground "#93e0e3"))))
 '(magit-cherry-equivalent ((t (:foreground "#dc8cc3"))))
 '(magit-reflog-commit ((t (:foreground "#00ff00"))))
 '(magit-reflog-amend ((t (:foreground "#dc8cc3"))))
 '(magit-reflog-merge ((t (:foreground "#00ff00"))))
 '(magit-reflog-checkout ((t (:foreground "#0000ff"))))
 '(magit-reflog-reset ((t (:foreground "#ff0000"))))
 '(magit-reflog-rebase ((t (:foreground "#dc8cc3"))))
 '(magit-reflog-cherry-pick ((t (:foreground "#00ff00"))))
 '(magit-reflog-remote ((t (:foreground "#93e0e3"))))
 '(magit-reflog-other ((t (:foreground "#93e0e3"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:inherit font-lock-comment))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#4c83ff"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#00ff00"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#ff1493" :weight bold))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#ffff00" :weight bold))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#ffff00" :weight bold))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#ffa500" :weight bold))))
 '(message-header-xheader ((((class color) (min-colors 89)) (:foreground "#00ff00"))))
 '(message-mml ((((class color) (min-colors 89)) (:foreground "#ffff00" :weight bold))))
 '(message-separator ((((class color) (min-colors 89)) (:inherit font-lock-comment))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "#add8e6" :background "#000000" :weight bold :height 1.5))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#add8e6" :background "#000000" :weight bold))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#8B8989" :background "#000000"))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:foreground "#FF6400" :slant italic :weight bold))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(org-archived ((((class color) (min-colors 89)) (:slant italic))))
 '(org-checkbox ((((class color) (min-colors 89)) (:background "#8B8989" :foreground "#000000" :box (:line-width 1 :style released-button)))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#00ffff" :underline t))))
 '(org-done ((((class color) (min-colors 89)) (:bold t :weight bold :foreground "#00ff00" :box (:line-width 1 :style none)))))
 '(org-todo ((((class color) (min-colors 89)) (:bold t :foreground "#ffa500" :weight bold :box (:line-width 1 :style none)))))
 '(org-level-1 ((((class color) (min-colors 89)) (:foreground "#ff1493" :height 1.3))))
 '(org-level-2 ((((class color) (min-colors 89)) (:foreground "#ffff00" :height 1.2))))
 '(org-level-3 ((((class color) (min-colors 89)) (:foreground "#4c83ff" :height 1.1))))
 '(org-level-4 ((((class color) (min-colors 89)) (:foreground "#00ff00"))))
 '(org-level-5 ((((class color) (min-colors 89)) (:foreground "#ffa500"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:foreground "#ff69b4"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:foreground "#afd8af"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:foreground "#7b68ee"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#96CBFE" :underline t))))
 '(org-tag ((((class color) (min-colors 89)) (:bold t :weight bold))))
 '(org-column ((((class color) (min-colors 89)) (:background "#4D4D4D" :foreground "#000000"))))
 '(org-column-title ((((class color) (min-colors 89)) (:background "#4D4D4D" :underline t :weight bold))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#dcdccc" :background "#383838"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:foreground "#008ED1" :background "#2b2b2b"))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:foreground "#008ED1" :background "#2b2b2b"))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit default))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit outline-8 :height 1.0))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit outline-7 :height 1.0))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit outline-6 :height 1.0))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit outline-5 :height 1.0))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit outline-4 :height 1.0))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit outline-3 :height 1.0))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit outline-2 :height 1.0))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#8b0000"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#006400"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#ff1493"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#ffff00"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#00ff00"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#add8e6"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#ffa500"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#6a5acd"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#d3d3d3"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:foreground "#9c6363" :background "#000000"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#000000" :background "#ff1493"))))
 '(term-color-black ((((class color) (min-colors 89)) (:foreground "#000000" :background "#2b2b2b"))))
 '(term-color-red ((((class color) (min-colors 89)) (:foreground "#8b0000" :background "#8c5353"))))
 '(term-color-green ((((class color) (min-colors 89)) (:foreground "#00ff00" :background "#9fc59f"))))
 '(term-color-yellow ((((class color) (min-colors 89)) (:foreground "#ffa500" :background "#ffff00"))))
 '(term-color-blue ((((class color) (min-colors 89)) (:foreground "#7b68ee" :background "#b2dfee"))))
 '(term-color-magenta ((((class color) (min-colors 89)) (:foreground "#dc8cc3" :background "#ff0000"))))
 '(term-color-cyan ((((class color) (min-colors 89)) (:foreground "#93e0e3" :background "#0000ff"))))
 '(term-color-white ((((class color) (min-colors 89)) (:foreground "#dcdccc" :background "#2b2b2b"))))
 '(which-func ((((class color) (min-colors 89)) (:foreground "#bfebbf"))))
 '(custom-button ((((class color) (min-colors 89)) (:box (:line-width 2 :style released-button) :background "#383838" :foreground "#dcdccc"))))
 '(custom-button-unraised ((((class color) (min-colors 89)) (:background "#383838" :foreground "#dcdccc"))))
 '(default ((t (:background "#000503" :foreground "#d3d3d3")))))

(provide-theme 'cyberpunk)
